[package]
name = "untitled5"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.17"
lazy_static = "1.4.0"
rand = "0.8.4"
async-std = { version = "1.10.0", features = ["attributes"] }
